-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Machine: 127.0.0.1
-- Gegenereerd op: 01 jun 2017 om 00:17
-- Serverversie: 5.6.17
-- PHP-versie: 5.5.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Databank: `portfolio`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `articles`
--

CREATE TABLE IF NOT EXISTS `articles` (
  `art_id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `title_small` varchar(100) NOT NULL,
  `article` text NOT NULL,
  `article_small` varchar(500) NOT NULL,
  `created_article` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `image_article` varchar(100) DEFAULT NULL,
  `youtube` varchar(120) DEFAULT NULL,
  PRIMARY KEY (`art_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=25 ;

--
-- Gegevens worden geëxporteerd voor tabel `articles`
--

INSERT INTO `articles` (`art_id`, `title`, `title_small`, `article`, `article_small`, `created_article`, `image_article`, `youtube`) VALUES
(1, 'Bicymple campagne', 'Bicymple everything changes.', 'Voor het vak "visuele communicatie" kregen we de opdracht om een aantal opmerkelijke of rare producten te promoten. Ik en mijn groep kregen het product "Bicymple".\r\n\r\n<br><br>\r\nDe Bicymple is een fiets die gebruikt kan voor het los besturen van voor- en achterwiel worden om makkelijk te navigeren door steden, maar ook om stunts op uit te voeren. Als groep was aan ons om een doelgroep, kernwaarden en een aantal unique selling points te koppelen aan de fiets om een campagne te vormen.\r\n\r\n<br><br>\r\nHet eindproduct was een campagne genaamd: "Bicymple. Everything changes". Het idee achter de campagne is dat het design van de doorsnee fiets iedere eeuw veranderd, dus deze eeuw vind er weer een verandering plaats: de Bicymple. Dit werd tot uiting gebracht in posters, een landingspage en een moodvideo.\r\n\r\n<br><br>\r\nOp een zelfgemaakte landingspage plaatste we een moodvideo ter ondersteuning van onze campagne. Op de landingspage kon je het thema van de pagina en de muziek onder de moodvideo veranderen door op de verschillende fietsdesigns door de eeuwen heen te klikken. Het was technisch niet van hoge kwaliteit door de middelmatige HTML/CSS kennis destijds, maar het concept kwam duidelijk over.\r\n\r\n<br><br>\r\nDeze groepsopdracht leerde ik om visuele middelen in te zetten om een product te promoten met een stukje strategie. Onze inspanning werd beloont met een 8.', 'Een schoolopdracht voor het vak visuele communicatie, waar het promoten en re-branden van het product "Bicymple" centraal stond. In groepsverband cre&euml;erde we een concept en werkte dit uit tot visuele uitingen.', '2016-05-24 10:23:21', '__poster3.jpg,__poster2.jpg,__poster1.jpg,bicymple_landingspage.jpg,bicymple.png', NULL),
(2, 'Rascal Games', 'The game is in your hands', 'Rascal Games was mijn eerste project op Fontys ICT. Met alle kennis van de 4 richtingen (Technology, Media Design, Software Engineering & Business) moesten we in groepsverband een product verzinnen en maken. Met mijn groep hebben we een game genaamd: "Platemania" en een console genaamd: "Digipult" in het leven geroepen.\r\n<br><br>\r\nOnze groep bestond uit 5 leden die we verdeelde over de richtig die ze het leukste vonden of waar ze het beste in waren. Ik richtte me voornamelijk op Media Design taken zoals de website en promotiemateriaal. \r\n<br><br>\r\nIn de foto''s hierboven zie je onze groep met de console en de game op de achtergrond. \r\n\r\n', 'Rascal Games was mijn eerste project op Fontys ICT. Met alle kennis van de 4 richtingen (Technology, Media Design, Software Engineering & Business) moesten we in groepsverband een product verzinnen en maken. Met mijn groep hebben we een game genaamd: "Platemania" en een console genaamd: "Digipult" in het leven geroepen.', '2016-05-24 12:00:24', 'rascal_logo.jpg,rascalgroup.jpg,rascalwebsite.jpg,rascal.jpg,plate_mania.jpg,rascal.png', NULL),
(3, 'Computer van de toekomst: Vision', 'Een voice recognition AR prototype', 'Vision is een klein, maar toekomstgericht project voor het vak "Experience Design". Het doel van de opdracht was om met behulp van een Arduino en een visualisatie een toekomstbeeld te schetsen voor de computer van de toekomst.  \r\n<br><br>\r\nEen hoop variabelen kome kijken bij het designen van een product dat nog niet zal bestaan voor tenminste 10+ jaar. De grootste design challenge was het designen voor de "lens", want wij denken dat we allemaal een lens zullen gebruiken in de toekomst. Omdat een mens 2 ogen heeft en moeilijk kan focussen met iets op de lens moesten we goed nadenken over de applicatie van het product en waar informatie te displayen.\r\n<br><br>\r\nAls Mediadesigner hebben we niet geleerd hoe we om moeteb gaab met een Arduino en C, vandaar dat we gebruik hebben gemaakt van een Arduino library "EasyVR" om een voice recognition prototype te kunnen laten zien aan onze docenten samen met een visualisatie. Het prototype herkende de commando''s "Accept" en "Deny" en liet hierbij een groen of rood lampje branden.\r\n<br><br>\r\nHet ging er bij dit project niet om om de beste visualisatie te maken, maar vooral om na te denken over de toekomst en buiten je comfort zone te stappen met een Arduino.\r\n', 'Vision is een klein, maar toekomstgericht project voor het vak "Experience Design". Het doel van de opdracht was om met behulp van een Arduino en een visualisatie een toekomstbeeld te schetsen voor de computer van de toekomst.  ', '2016-05-27 14:49:54', 'stopmotion.jpg,arduinocode.jpg,arduino.jpg,vision.jpg,arduino_small.jpg', 'TV_pRT4fdE0'),
(4, 'Logo designing proces', 'Sometimes I hate Adobe Illustrator', 'Dit design van mijn website heeft niet zo zeer een logo nodig als de meeste websites vanwege het krant-design. Mijn logo is toch terug te vinden op mijn visitekaartjes en ook hier bij mijn projecten, er zit namelijk een flink proces achter.\r\n\r\n<br><br> \r\nIn de afbeelding slider is mijn chronologische logo design proces te vinden. Ik ben van een tandwiel steampunk design dat niet echt bij mij paste, naar een zwart-wit simpel logo gegaan. Ik heb voor een schoolopdracht ruim 100 logo''s moeten maken, echter na deze 100 had ik toch mijn eigen logo nog niet gevonden. Uiteindelijk ben ik verder gegaan met een "American Diner" achtig font en cirkel logo. Het logo is simpel en past niet alleen bij dit portfolio, maar is ook nog eens toe te passen in verschillende kleuren bij andere projecten.\r\n', 'In dit artikel lees en zie je mijn eigen logo-design proces en de verschillende versies van mijn uiteindelijke logo. ', '2016-05-27 14:55:38', 'logo_versie2.png,diner.jpg,shirts.jpg,logotrans.png,process_logo.jpg,old_logos.jpg,logo_versie2.png', ''),
(5, 'Een poster voor een feest', '3D modellen voor een poster?', 'Voor een groepsopdracht heb uit eigen initiatief een poster gemaakt voor een feest genaamd "Reistas" dat we moesten branden en organiseren. Nu is een poster op zichzelf niet zo interessant, maar bij het maken van deze poster heb ik gebruik gemaakt van een tal van interessante technieken.\r\n<br><br>\r\nIk kon geen geschikt model vinden voor een poster op het internet, mede omdat mijn budget voor afbeeldingen exact €0 was. Ik besloot om een eigen model te maken. Met het programma "Adobe Fuse" heb ik een model naar mijn visie gemaakt en ge&euml;porteerd naar Adobe Photoshop waar ik het model "rig" in een pose en de belichting , logo en een rugzak heb toegevoegd. \r\n<br><br>\r\nToen ik klaar was met het model heb ik ge&euml;xperimenteerd met verschillende achtergronden en tekst. De verschillende versies zijn zichtbaar in de slider. Ondanks dat mijn poster uiteindelijk niet gebruikt is voor het feest, ben ik toch blij dat ik nu modellen kan maken en inzetten voor posters.', 'Voor een groepsopdracht heb uit eigen initiatief een poster gemaakt voor een feest genaamd "Reistas" dat we moesten branden en organiseren. Nu is een poster op zichzelf niet zo interessant, maar bij het maken van deze poster heb ik gebruik gemaakt van een tal van interessante technieken.', '2016-05-27 16:21:27', '3dmodelprocess.jpg,reistaseind.jpg,reistas4.jpg,reistas3.jpg,reistasoposter2.jpg,reistasdposeter1.jp', NULL),
(6, 'Typografie posters', 'Inspirational quote galore', 'Voor een opdracht vanuit school heb ik verschillende typografische posters gemaakt. Ik heb niet alleen leren omgaan met verschillende fonts en text plaatsing, maar heb me ook laten inspireren door Amerikaans design. Het is geen moeilijke opdracht, maar ik be blij met het resultaat. \r\n<br><br>\r\nDe posters staan in volgorde van creatie & feedback, dus het proces is duidelijk te zien.', 'Voor een opdracht vanuit school heb ik verschillende typografische posters gemaakt. Ik heb niet alleen leren omgaan met verschillende fonts en text plaatsing, maar heb me ook laten inspireren door Amerikaans design. ', '2016-06-11 10:45:23', 'enpathy.jpg,coffee.jpg,posterwasmiddel.jpg,oppengeimer.jpg,typopreview.jpg', NULL),
(7, 'Rust', 'Het is niet fijn, maar zeker mooi', 'In deze photo serie laat is mijn beste foto''s omtrent 1 thema zien: roest. Ik vind roest een bijzonder fenomeen en toen ik vanuit school met een camera moest leren omgaan ging ik opzoek naar roestige plaatsen.\r\n<br><br>\r\nDit zijn enkele van mijn eerste foto''s met een spiegelreflex camera en zijn dus nog niet van een professionele kwaliteit. Als je meer wilt zien van mijn fotografie kunsten klik dan <a href="https://www.flickr.com/gp/140303918@N02/fghb61">Hier</a>. ', 'In deze photo serie laat is mijn beste foto''s omtrent 1 thema zien: roest. Ik vind roest een bijzonder fenomeen en toen ik vanuit school met een camera moest leren omgaan ging ik opzoek naar roestige plaatsen.', '2016-06-11 12:46:15', 'reeks1p3.jpg,reeks1p2.jpg,reeks1p1.jpg,r1preview.jpg', NULL),
(8, 'Mirror mirror on the....pole?', 'Wie lijmt er nu spiegels op palen?', 'Wat begon als een middag foto''s nemen van moderne architectuur voor een schoolopdracht eindigde met foto''s van een formatie palen op een rotonde. De palen stonden midden op een rotonde en hadden ieder een spiegel op de schuine top gelijmd. In het midden van de rotonde stond een plateau wat leek op een offertafel. Het was een appart beeld, maar zeker de moeite waard om een foto van te maken.\r\n\r\n<br><br>\r\nIk heb de foto''s gemaakt op een drukke rotonde, ik kreeg verschillende blikken van voorbijgangers, maar soms moet je rare dingen doen om de beste foto''s te maken.\r\n', 'Wat begon als een middag foto''s nemen van moderne architectuur voor een schoolopdracht eindigde met foto''s van een formatie palen op een rotonde.', '2016-06-11 13:03:29', 'r2p2.jpg,r2p5.jpg,r2p4.jpg,r2p3.jpg,r2p1.jpg,r2preview.jpg', NULL),
(9, 'Beschadigd maar niet lelijk', 'Kijk naar die kleuren!', 'Nog een poging tot het maken van een set moderne fotografie foto''s maar ik zag een verlaten zwembad en een skatepark dichtbij en kon het niet weerstaan een paar foto''s te nemen. In deze fotoserie ben ik op een verboden terrein geweest om mijn foto''s te realiseren, maar het is het waard.', 'Nog een poging tot het maken van een set moderne fotografie foto''s maar ik zag een verlaten zwembad en een skatepark dichtbij en kon het niet weerstaan een paar foto''s te nemen.', '2016-06-11 13:26:14', 'r3p1.jpg,r3p3.jpg,r3p2.jpg,r3preview.jpg', NULL),
(10, 'Creepy stones', 'It''s petrifying!', 'Nog een fotoserie, maar dit keer van de verlaten tramlijn in het dorp Goirle. Ik wist dat foto''s van oude of vervallen gebouwen er vaak goed uitzien, vandaar dat ik op mijn vrije middag een set foto''s ben gaan maken in het bos van Goirle. \r\n<br><br>\r\nIn de foto''s heb ik gebruik gemaakt van verschillende perspectieven terwijl er diffuus licht aanwezig was door het weer. Dit gaf de foto''s een mooi duister uiterlijk zonder enige bewerking.', 'Nog een fotoserie, maar dit keer van de verlaten tramlijn in het dorp Goirle. Ik wist dat foto''s van oude of vervallen gebouwen er vaak goed uitzien, vandaar dat ik op mijn vrije middag een set foto''s ben gaan maken in het bos van Goirle.', '2016-06-11 13:46:52', 'r4p5.jpg,r4p3.jpg,r4p1.jpg,r4p4.jpg,r4p2.jpg,r4preview.jpg', NULL),
(11, 'Portret fotografie', 'Zo moeilijk kan het toch niet zijn...?', 'Een andere schoolopdracht waar ik eigen modellen moest kiezen om portretfoto''s van te maken. Ik moest bij de opdracht rekening houden met het weer, de achtergrond en zoom va de foto. ', 'Een andere schoolopdracht waar ik eigen modellen moest kiezen om portretfoto''s van te maken. Ik moest bij de opdracht rekening houden met het weer, de achtergrond en zoom va de foto. ', '2016-06-11 14:01:26', 'stephan1.jpg,Cas2.jpg,cas1.jpg,stephanklein.jpg', NULL),
(12, 'Fotografie in het donker', 'Moeilijker dan het lijkt', 'In deze verbetering van mijn portretfotografie opdracht besloot ik te gaan experimenteren met belichting in het donker. Ik heb het model verschillende kleuren licht laten projecten onder haar gezicht en ondervond hoe moeilijk het is om zo foto''s te maken.', 'In deze verbetering van mijn portretfotografie opdracht besloot ik te gaan experimenteren met belichting in het donker. Ik heb het model verschillende kleuren licht laten projecten onder haar gezicht en ondervond hoe moeilijk het is om zo foto''s te maken.', '2016-06-11 14:06:45', 'r5p1.jpg,r5p5.jpg,r5p4.jpg,r5p3.jpg,r5p2.jpg,r5preview.jpg', NULL),
(13, 'Bedenk en brand een product in 1 uur!', 'Lijkt onmogelijk toch?', 'Een van onze docenten (Pieter Dorst) gaf onze klas een interessante spontane opdracht: brand en bedenk een product in slechts 1 uur. We kregen enkel een foto van een flesje met de vraag: "Wat zit er in dit flesje?". Aan ons om de doelgroep, visuele identiteit, product naam, logo en natuurlijk hey product zelf te verzinnen.\r\n<br><br>\r\nMet een groep van 3 leerlingen waaronder ik zelf bedachte we het product "Tastebuds". Een hoge klasse honing likeur met als doelgroep vrouwen van  30 die af en toe wel eens een wijntje drinken, maar op zijn tijd toe zijn aan iets anders.\r\n<br><br>\r\nWe maakte in het uur een hele simpele poster in Photoshop die je hierboven kunt zien. Het mag dan wel geen professioneel product zijn, toch hebben we de uitdaging om het in 1 uur te doen succesvol gehaald. ', 'Een van onze docenten (Pieter Dorst) gaf onze klas een interessante spontane opdracht: brand en bedenk een product in slechts 1 uur. We kregen enkel een foto van een flesje met de vraag: "Wat zit er in dit flesje?". Aan ons om de doelgroep, visuele identiteit, product naam, logo en natuurlijk hey product zelf te verzinnen.', '2016-06-11 15:21:47', 'bottle.jpg,tastebudsposter.jpg,logobig.jpg,bottle small.jpg', NULL),
(14, 'Mijn eerste website', 'Niet zo slecht dan je zou denken', 'I must admit, this wasn''t the first time I had worked with HTML/CSS but this is in fact my first website. I didn''t just make the website without thinking about what I wanted to make.\r\n<br><br>\r\nWhile making the website I had to do several things before I could start coding. I had to make an analysis of the target audience, a moodboard, relevant content, a logo, sketches and a sitemap. \r\n<br><br>\r\nNot only did I learn to code while coding the website, I also learned all the things above and why they''re needed in order to make a successful website.\r\n\r\nIk moet toegeven, toen ik de opdracht in de eerste week van school kreeg om een website te maken had ik al wat met HTML/CSS gedaan, maar ik feite is dit mijn eerste website. Ondanks mijn kennis was het doel van de opdracht om het ontwerpproces van een website te leren.\r\n<br><br>\r\nTijdens het maken van de website heb ik een moodboard, logo, relevante content, schetsen en een sitemap gemaakt. Dit proces is nu een proces dat ik doorloop bij de creatie van iedere website. \r\n<br><br>\r\nDe website is <a href="http://athena.fhict.nl/users/i313040/projects/periode1/Index.html">Hier</a> te vinden!\r\n\r\n', 'De eerste opdracht voor Media Design op school was "maak een website voor je eigen Media Design school". Ik had geen tot weinig kennis van HTML/CSS en heb toch een goede website afgeleverd. ', '2016-06-11 18:36:41', 'vortislogo.jpg,Vortis contact.jpg,vortisvideo.jpg,vortisfront.jpg,vortis small.jpg', NULL),
(15, 'Hologrammen in Photoshop', 'Een kleine DJ heeft hologram doppelgangers!', 'Voor een groepsproject werd ons de opdracht voorgelegd om een kleine plaatselijke DJ "Robin Riccio" te branden. Hij vroeg om een logo en website, maar onze lerare moedigde ons aan om verder te kijken dan een logo en website. Ik heb wat extra werk verricht en had een visie op de toekomst van DJ entertainment.\r\n<br><br>\r\nRobin had wat typerende kenmerken zoals dat hij zijn hand op de beat in de lucht stak bij een drop om het publiek te entertainen. De voorste rij op een festival kan hem dat zien doen, maar de achterste rij bijvoorbeeld niet. Dit is waarom ik een concept heb bedacht waarin Robin ook het publiek achterin kan entertainen door middel van hologram dubbelgangers. Ik heb een proof of concept gemaakt in Photoshop en Premiere Pro en later heb ik het echte hologram gemaakt.\r\n\r\n<br><br> Credits gaan aan Robin Riccio voor zijn merknaam', 'In dit (groeps)project moest ik een plaatselijke DJ Robin Ricio branden. Naast een website en logo heb ik ook mijn visie van DJ entertainment uitgewerkt met een bijzonder proof of concept...', '2016-11-24 21:24:09', 'Robingiffio.gif,cutbig.png,cutsmall.png', ''),
(16, 'Een echt hologram?!', 'En jij dacht dat alleen Tupac het kon?', 'Dit project is een innovatief project waar ik echt trots op ben. In plaats van duur materiaal te kopen of lenen heb ik met tape, Adobe software en wat plastic een hologram gemaakt. \r\n<br><br>\r\nDe DJ die ik in dit groepsproject moest branden (Robin Riccio) is de persoon die in de video hierboven als hologram danst. Ik heb het bovenstaande hologram met Adobe Fuse gemaakt op het postuur en de uiterlijke kenmerken van Robin Riccio. Vervolgens heb ik het 3D model uit Fuse gehaald en geanimeerd met de 3D model rigging in Photoshop. \r\n<br><br>\r\nHet daadwerkelijke hologram is gemaakt door een prisma te maken met wat plastic en tape en vervolgens de animatie 4x te dupliceren aan alle zijden op een scherm onder het prisma. Ik ben erg tevreden met hoe het heeft uitgepakt.\r\n\r\n', 'Dit project is een innovatief project waar ik echt trots op ben. In plaats van duur materiaal te kopen of lenen heb ik met tape, Adobe software en wat plastic een hologram gemaakt.', '2016-11-24 22:42:39', 'ezgif.com-6a0bd4ba87.gif,ezgif.com-9c79d5dea0.gif,3dkappross.png', 'MSprFWJNwTw'),
(17, 'Filmatic: a location based movie app', 'Concepting & Swift ervaring, yes please!', 'Ik heb de innovatieroute "Smart-Mobile iOS" gedaan, omdat ik meer wilde leren omtrent app ontwikkeling en de programmeertaal Swift. Een opdracht binnen deze innovatieroute was de ontwikkeling van een innovatieve duo-app met een klasgenoot. Ik heb samen met Cas Hutten een proof of concept van een app gemaakt, die het makkelijker maakt voor frequente filmgebruikers om bij te houden welke films ze hebben bekeken. Het algoritme zou voorspellen naar welke film ze zouden gaan met behulp van geocaching. \r\n<br><br>\r\nIk was voornamelijk verantwoordelijk binnen het project voor user-testen & interaction design terwijl mijn partner voornamelijk het programmeer werk deed. Ik testte de online prototype app met potentiële gebruikers bij de bioscoop en schreef het app-concept document waarmee de app gepubliceerd zou kunnen worden. Ook droeg ik bij aan het UI ontwerp zowel online in Xcode als offline.\r\n<br><br>\r\nHet online clickable prototype is <a href="https://prottapp.com/p/a21959#/s/5810fa3286e4655bf55d0926">Hier</a> te vinden.', 'Ik heb de innovatieroute "Smart-Mobile iOS" gedaan, omdat ik meer wilde leren omtrent app ontwikkeling en de programmeertaal Swift. Een opdracht binnen deze innovatieroute was de ontwikkeling van een innovatieve duo-app met een klasgenoot.', '2016-11-24 23:01:38', 'cutbignoteTESS.png,cutbignoteLOGAN.png,cutbignoteTIMO.png,cutsmallTimo.png', '7T_JiND_guU'),
(18, 'IDEO: Human Centered Design', 'Social & community driven design', 'Ik heb in mij 3e semester meegedaan aan een internationaal groepsproject: IDEO Human Centered Design. In deze design workshop van 8x 1 dag beantwoordde we de vraag: "How Might We Enable More Young People to Become Social Entrepreneurs?".\r\n<br><br>\r\nDoor verschillende interviews af te nemen met sociale entrepreneurs identificeerde we een probleem dat we met de IDEO cursus stapsgewijs zouden oplossen. Het probleem was dat jonge entrepreneurs niet of te weinig professionele begeleiding en hierdoor faalt hun concept vaker. \r\n<br><br>\r\nDoor wat rapid prototyping hebben we een concept omtrent een on- en offline platform waar jonge entrepreneurs advies kunnen vragen ontwikkeld. "Thinktank" is een platform waar deze entrepreneurs letterlijk en figuurlijk naar advies kunnen vissen. ', 'Ik heb in mij 3e semester meegedaan aan een internationaal groepsproject: IDEO Human Centered Design. In deze design workshop van 8x 1 dag beantwoordde we de vraag: "How Might We Enable More Young People to Become Social Entrepreneurs?".', '2016-11-24 23:16:54', 'cutbigfishes.png,cutbigfish.png,cutbignoteVR.png,cutbignote.png,cutsmalltankfishcoral.png', NULL),
(19, 'Digital Comic', 'Ricky: Master of Space & Time', 'Ik ben een enorme stripboeken fan zoals je misschien op mijn homepage al hebt gelezen. Toen ik op school de kans geef om een digital comic te maken als vrij project, pakte ik deze kans met beide handen.\r\n<br><br>\r\nVoor de comic die ik heb gemaakt heb ik verschillende story- en moodboards gemaakt voor mijn verhaal. Ik ben een enorme superhelden lover, dus ik heb mezelf omgetoverd tot een superheld die tijd kan manipuleren. \r\n<br><br>\r\nZoals je al misschien wel ziet is mijn comic niet af, omdat ik er slechts een week aan gewerkt heb, maar het was een leuke ervaring. De eerste 2 pagina''s zijn ook <a href="http://www.comic.rickyrekkers.nl/index.html"> Hier</a> te vinden.', 'Ik ben een enorme stripboeken fan zoals je misschien op mijn homepage al hebt gelezen. Toen ik op school de kans geef om een digital comic te maken als vrij project, pakte ik deze kans met beide handen.', '2016-11-24 23:41:05', 'ezgif.com-ce181a927c.gif,cutsmallRICKY.png', NULL),
(20, 'Old School presentatie skills', 'Geen idee hoe ze dit vroeger deden', 'Er was geen reden om een unieke presentatie te geven voor mij propedeuse assessment, maar als mediadesigner voelde ik de drang om iets unieks te maken, een simpele presentatie voldeed niet. \r\n<br><br>\r\nOp een rommelmarkt heb ik een ouderwetse projector met dia slides gekocht en heb zelf mijn dia slides geprint op speciaal plastic. Zo kon ik een unieke authentieke presentatie geven aan mijn docenten. Ze waren het met me eens en gaven me niet alleen een 8/10, maar ook nog eens veel lof voor de presentatievorm.', 'Er was geen reden om een unieke presentatie te geven voor mij propedeuse assessment, maar als mediadesigner voelde ik de drang om iets unieks te maken, een simpele presentatie voldeed niet. ', '2016-11-25 00:05:05', 'Prsentsibig.png,cutbignoteDIA.png,cutsmallPRSENTS.png', 'sKoOVsLVmTg'),
(21, 'Een Twitch chatbot', 'Moeilijk, maar zeer zeker nodig', 'Voor een persoonlijk project dat ik uiteindelijk voor school heb ingezet, heb ik een chatbot voor de game-streaming website Twitch.tv gemaakt. Ik heb in de chatdienst mIRC met een paar scripts een bot in elkaar gezet die verschillende commando''s en woorden herkent als een gebruiker iets typt in de chat. De bot reageert op de gebruiker met de informatie die hij/zij wil van de bot. \r\n<br><br>\r\nIk heb met de scripting taal van mIRC verschillende functies in de bot geprogrammeerd zoals een puntensysteem, geautomatiseerde links met een timer en een "ban phrase". Deze functie komen voort uit persona''s (zie de slider) die ik heb gemaakt na een aantal interviews en enquÃªtes met de gebruikers. \r\n<br><br>\r\nDe bot die ik heb gemaakt is open source en te vinden op GitHub. Klik <a href="https://github.com/perceh/TwitchBot">Hier</a> om de pagina te bekijken. ', 'Voor een persoonlijk project dat ik uiteindelijk voor school heb ingezet, heb ik een chatbot voor de game-streaming website Twitch.tv gemaakt. Ik heb in de chatdienst mIRC met een paar scripts een bot in elkaar gezet die verschillende commando''s en woorden herkent als een gebruiker iets typt in de chat.', '2017-04-08 16:48:37', 'twitch_bot_big.png,persona_aaron.png,persona_david.png,persona_julian.png,Twitch_small.png', ''),
(22, 'Unwanted, een 3D geprint bordspel', 'Voor Indicia & Genicap', 'Vanuit school kregen we een opdracht aangereikt vanuit het bedrijfsleven. Indicia was samen met de 3D printer ontwikkelaar Genicap bezig om een formule die de structuur van 3D modellen makkelijker maakte vorm te geven. In groepsverband kregen we de vrije opdracht om de software waar Indicia mee bezig was te promoten en/of een nieuwe toepassing hierop te verzinnen.\r\n<br><br>\r\nAls groep besloten we na wat onderzoek en verschillende concepting sessies dat we de software van Indicia & Genicap wilde inzetten in de bordspel markt. Nu denk je bordspellen?! En toch blijkt dat er op zowel de on- als offline game markt er veel vraag is naar speluitbreidingen. Wij bedachten dat we basispakketten op de markt brengen en dat Indicia hun communityplatform kan inzetten om tegen betaling extra tegels, figuurtjes en middenstukken kan printen voor hun klanten.\r\n<br><br>\r\nUiteindelijk hebben we voor Indicia een prototype bordspel inclusief een Arduino integratie prototype gebouwd. Ik ben veel met 3D printers en 3D modellen bezig geweest tijdens het ontwikkelproces, omdat het gehele bordspel met een 3D printer is gemaakt. De tegels komen van de 3D printer, net als de tempel in het midden, maar ook het bord zelf komt uit een laserprinter. \r\n<br><br>\r\nAl met al hebben we veel plezier gehad met het project en ook nog eens veel met low-fi 3D prototyping gewerkt. Bij onze presentatie bleek dat we er met ons project niet ver naast zaten; Indicia zet de software in voor online gameontwikkeling. \r\n<br><br>\r\nDe presentatie en speluitleg zijn <a href="../uploads/pres_indicia.pdf">Hier</a> en <a href="../uploads/unwanted_rules.pdf">Hier</a> te vinden!', 'Vanuit school kregen we een opdracht aangereikt vanuit het bedrijfsleven. Indicia was samen met de 3D printer ontwikkelaar Genicap bezig om een formule die de structuur van 3D modellen makkelijker maakte vorm te geven. In groepsverband kregen we de vrije opdracht om de software waar Indicia mee bezig was te promoten en/of een nieuwe toepassing hierop te verzinnen.', '2017-04-08 17:21:44', 'temple_big.png,temple_side.png,Temple_blueprint.png,speelbord_temple.png,arduino_speelbord.png,3d_te', ''),
(23, 'Feed', 'Een augmented reality concept', 'Voor mijn innovatieroute op school heb ik samen met een groep een concept uitgewerkt voor het bedrijf "D-Centralize". De eigenaar van het bedrijf kwam naar ons met de probleemstelling: "Hoe kan ik mijn bedrijf zonder baas voortzetten?". Aan ons was om vanuit het "Holacracy" principe een concept in de vorm van een app of oplossing aan te bieden.\r\n<br><br>\r\nEr zaten geen restricties aan de opdracht vanuit de docenten, behalve dat ons concept en de uitwerking innovatief moesten zijn. Als mediadesigner in de groep ging er bij mij een lampje branden. Ik bedacht een innovatief concept dat Big Data inzet om via een Augmented Realty UI conversatie tijdens team meetings te cre	&euml;ren in plaats van de functioneringsgesprekken door een baas.\r\n<br><br>\r\nHierboven zie je een promotievideo die ik heb gemaakt voor ons product. Ik heb de UI, het concept en de interaction design van het product gemaakt. Ook hebben we met onze groep aan paper prototyping gedaan voordat we over gingen op applicatie design. Er is namelijk ook nog een C# applicatie geschreven door de software engineers in onze groep, maar meer ter onderbouwing van ons concept, wij hadden namelijk weken lang succesvol gebruik gemaakt van de applicatie.', 'Voor mijn innovatieroute op school heb ik samen met een groep een concept uitgewerkt voor het bedrijf "D-Centralize". De eigenaar van het bedrijf kwam naar ons met de probleemstelling: "Hoe kan ik mijn bedrijf zonder baas voortzetten?". Aan ons was om vanuit het "Holacracy" principe een concept in de vorm van een app of oplossing aan te bieden.', '2017-04-08 18:13:03', 'Feed_small.png', 'NMmJWkQ2Wsw'),
(24, 'Countries', 'Een Apple Watch app', 'Ik heb al een tijdje een Apple Watch en ik vond het interessant om iets ervoor te ontwikkelen nadat ik mijn innovatieroute Smart Mobile had gedaan. Er was destijds nog niet te veel documentatie en er waren maar weinig tutorials. Toch besloot ik iets te maken voor mijn watch.\r\n<br><br>\r\nSamen met een tutorial heb ik een kleine watch app gemaakt die informatie over verschillende landen verstrekt aan reizigers. De app geeft naast de huidige tijd, ook de hoofdstad, de taal, de valuta en handige omgang tips weer. \r\n<br><br>\r\nHet is geen bijzonder groot project, maar het is zeker leuk om dingen te ontwikkelen voor de Apple Watch en ook zeker noemenswaardig in dit portfolio dat ik hier iets mee gedaan heb.', 'Ik heb al een tijdje een Apple Watch en ik vond het interessant om iets ervoor te ontwikkelen nadat ik mijn innovatieroute Smart Mobile had gedaan. Er was destijds nog niet te veel documentatie en er waren maar weinig tutorials. Toch besloot ik iets te maken voor mijn watch.', '2017-04-08 18:30:32', 'watch_big.png,watch_big2.png,big_watch.png,watch_small.png', '');

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `comment`
--

CREATE TABLE IF NOT EXISTS `comment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `comment` varchar(100) NOT NULL,
  `stars` int(11) NOT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` varchar(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=4 ;

--
-- Gegevens worden geëxporteerd voor tabel `comment`
--

INSERT INTO `comment` (`id`, `comment`, `stars`, `created`, `user_id`) VALUES
(1, 'Dit is een comment van mezelf, ik hoop dat ik zo een goede opmaak krijg', 4, '2016-05-27 12:11:57', '1'),
(2, 'Keepo123', 4, '2016-05-27 12:48:43', '3'),
(3, 'lolucvuycvyhuvvyyvyuvyvyivyvyuyvyu', 3, '2016-06-09 23:30:51', '1');

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `users`
--

CREATE TABLE IF NOT EXISTS `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `level` varchar(6) DEFAULT NULL,
  `username` varchar(20) NOT NULL,
  `password` varchar(255) NOT NULL,
  `email` varchar(100) NOT NULL,
  `created_user` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=10 ;

--
-- Gegevens worden geëxporteerd voor tabel `users`
--

INSERT INTO `users` (`user_id`, `level`, `username`, `password`, `email`, `created_user`) VALUES
(1, 'admin', 'ricky', '$2y$10$xT/iQinR3G15yIfe1IdPNOlZlJ.VDVDfvoac3851IlHj6Jj1ppIqm', 'rickyrekkers@hotmail.com', '2016-05-17 17:56:53'),
(3, 'leraar', 'keepo', '$2y$10$aDkLd6FE15AqSFRYH7gCJudZsJS/bwTlo/y4KezAXdHK2f8.PSGfO', 'rickyrekkers@hotmail.com', '2016-05-17 18:29:55'),
(4, 'leraar', 'new', '$2y$10$EdaIxZADgAWSskQkbOXiqO2UCpSi99g0ThisPLwEbzCi8DBZKyEJa', 'rickyrekkers@hotmail.com', '2016-05-24 07:54:26'),
(5, NULL, 'test', '$2y$10$3iFlLpj4TYHZjL/fCXFSjOWvopN3iL52CvTP7713/hhP2IqKS/vkO', 'rickyrekkers@hotmail.com', '2016-06-01 07:49:31'),
(6, NULL, 'kappa123', '$2y$10$VdF2ZMstmcePWmOaJY.PEOOR8gYAopLrZeP2EAWoRfZlr6w981yJm', 'kappa123@hotmail.com', '2016-06-10 14:51:40'),
(7, NULL, 'kappa5', '$2y$10$USzVOJ1Z8SHXgckVV6/tEu78608BL4Ov2l7BpnCgAYGlIaO4UFo9O', 'rickyrekkers@hotmail.com', '2016-06-10 15:15:17'),
(8, NULL, 'wik', '$2y$10$wtL7bF7ZK7qcQj55CD3h8ONVK1UuEBlxWSdlnl0f1ndBYIGOp/71G', 'rickyrekkers@hotmail.com', '2016-06-10 15:40:25'),
(9, 'admin', 'meh', '$2y$10$xflYQif5oItk0d5PPsX5KulXW/5G3ioBn1BokzkBoCROFq8ze4cGC', 'rickyrekkers@hotmail.com', '2017-03-20 21:34:57');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
